# Generated by Django 4.1.7 on 2023-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movmensalista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='valor_mes',
        ),
        migrations.AddField(
            model_name='mensalista',
            name='mensalista',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
