# Generated by Django 4.1.7 on 2023-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='recebernoticias',
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(max_length=200),
        ),
    ]
